---
title: "An introduction to NuisanceParameters"
author:
  - Michael Knaus
  - Stefan Glaisner
date: "`r format(Sys.time(), '%B %d, %Y')`"
bibliography: ../assets/NuisanceParameters_refs.bib
link-citations: true
output:
  rmarkdown::html_vignette:
    fig_width: 8
    fig_height: 6
    toc: true
    code_folding: show
vignette: >
  %\VignetteIndexEntry{An introduction to NuisanceParameters}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, include=FALSE}

rm(list=ls())
gc()

hook_output <- knitr::knit_hooks$get("output")

knitr::knit_hooks$set(output = function(x, options) {
  if (!is.null(n <- options$out.lines)) {
    x <- xfun::split_lines(x)
    if (length(x) > n) {
      x <- c(head(x, n), "....\n")
    }
    x <- paste(x, collapse = "\n")
  }
  hook_output(x, options)
})

```

This notebook provides a detailed overview over the `NuisanceParameters` package developed on the basis of @knaus.


# Getting started

The very latest version of the package can be installed from its [Github page](https://github.com/stefan-1997/NuisanceParameters). For the installation you will need the `devtools` package.

```{r startup, eval=FALSE, error=FALSE, warning=FALSE, message=FALSE}

library(devtools)
devtools::install_github("stefan-1997/NuisanceParameters")

```

Load `NuisanceParameters` using `library()`.

```{r load}

library(NuisanceParameters)

```

# References
